import { Camera } from './types';

export const MOCK_CAMERAS: Camera[] = [
  {
    id: 'i10-east-executive',
    name: 'I-10 East at Executive Center',
    location: 'Executive Center Blvd & I-10 East',
    latitude: 31.758,
    longitude: -106.289,
    highway: 'I-10',
    neighborhood: 'Eastside',
    imageUrl: 'https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=800&q=80',
    lastUpdated: new Date().toISOString(),
    status: 'active',
    cameraType: 'traffic',
    description: 'Eastbound traffic monitoring at Executive Center',
  },
  {
    id: 'i10-west-anthony',
    name: 'I-10 West near Anthony, NM',
    location: 'I-10 West near New Mexico Border',
    latitude: 31.647,
    longitude: -106.708,
    highway: 'I-10',
    neighborhood: 'Westside',
    imageUrl: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=80',
    lastUpdated: new Date().toISOString(),
    status: 'active',
    cameraType: 'traffic',
    description: 'Westbound traffic on I-10 near state border',
  },
  {
    id: 'us54-north-i10',
    name: 'US-54 North at I-10',
    location: 'US-54 North & I-10 Interchange',
    latitude: 31.778,
    longitude: -106.435,
    highway: 'US-54',
    neighborhood: 'Central',
    imageUrl: 'https://images.unsplash.com/photo-1446776877081-d282a0f896e2?w=800&q=80',
    lastUpdated: new Date().toISOString(),
    status: 'active',
    cameraType: 'traffic',
    description: 'Northbound traffic at US-54 and I-10 junction',
  },
  {
    id: 'loop-375-east-yarbrough',
    name: 'Loop 375 East at Yarbrough',
    location: 'Loop 375 East & Yarbrough Drive',
    latitude: 31.839,
    longitude: -106.338,
    highway: 'Loop-375',
    neighborhood: 'Northeast',
    imageUrl: 'https://images.unsplash.com/photo-1533473359331-35acda7ce3ad?w=800&q=80',
    lastUpdated: new Date().toISOString(),
    status: 'active',
    cameraType: 'traffic',
    description: 'Eastbound Loop 375 monitoring near Yarbrough',
  },
  {
    id: 'loop-375-west-airway',
    name: 'Loop 375 West at Airway Boulevard',
    location: 'Loop 375 West & Airway Boulevard',
    latitude: 31.760,
    longitude: -106.553,
    highway: 'Loop-375',
    neighborhood: 'Westside',
    imageUrl: 'https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=800&q=80',
    lastUpdated: new Date().toISOString(),
    status: 'active',
    cameraType: 'traffic',
    description: 'Westbound Loop 375 traffic conditions',
  },
  {
    id: 'downtown-oregon-st',
    name: 'Downtown at Oregon Street',
    location: 'Oregon Street & Downtown Area',
    latitude: 31.756,
    longitude: -106.497,
    highway: 'Other',
    neighborhood: 'Central',
    imageUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&q=80',
    lastUpdated: new Date().toISOString(),
    status: 'active',
    cameraType: 'traffic',
    description: 'Downtown El Paso traffic monitoring',
  },
  {
    id: 'mesa-st-i10',
    name: 'Mesa Street at I-10',
    location: 'Mesa Street & I-10 Interchange',
    latitude: 31.751,
    longitude: -106.412,
    highway: 'I-10',
    neighborhood: 'Central',
    imageUrl: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=80',
    lastUpdated: new Date().toISOString(),
    status: 'active',
    cameraType: 'traffic',
    description: 'Central El Paso I-10 traffic conditions',
  },
  {
    id: 'eastmorland-blvd',
    name: 'Eastmorland Boulevard',
    location: 'Eastmorland Boulevard & Loop 375',
    latitude: 31.809,
    longitude: -106.289,
    highway: 'Loop-375',
    neighborhood: 'Eastside',
    imageUrl: 'https://images.unsplash.com/photo-1446776653964-20c1d3a81b06?w=800&q=80',
    lastUpdated: new Date().toISOString(),
    status: 'active',
    cameraType: 'traffic',
    description: 'Eastside traffic monitoring at Eastmorland',
  },
  {
    id: 'montana-ave-central',
    name: 'Montana Avenue - Central',
    location: 'Montana Avenue & Downtown',
    latitude: 31.757,
    longitude: -106.483,
    highway: 'Other',
    neighborhood: 'Central',
    imageUrl: 'https://images.unsplash.com/photo-1533473359331-35acda7ce3ad?w=800&q=80',
    lastUpdated: new Date().toISOString(),
    status: 'active',
    cameraType: 'traffic',
    description: 'Central downtown traffic monitoring',
  },
  {
    id: 'yarbrough-northeast',
    name: 'Yarbrough Drive - Northeast',
    location: 'Yarbrough Drive & Loop 375',
    latitude: 31.859,
    longitude: -106.325,
    highway: 'Other',
    neighborhood: 'Northeast',
    imageUrl: 'https://images.unsplash.com/photo-1526439773649-619f2ea80086?w=800&q=80',
    lastUpdated: new Date().toISOString(),
    status: 'active',
    cameraType: 'traffic',
    description: 'Northeast El Paso traffic conditions',
  },
  {
    id: 'sunland-park-west',
    name: 'Sunland Park Drive - West',
    location: 'Sunland Park Drive & Westside',
    latitude: 31.733,
    longitude: -106.588,
    highway: 'Other',
    neighborhood: 'Westside',
    imageUrl: 'https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=800&q=80',
    lastUpdated: new Date().toISOString(),
    status: 'active',
    cameraType: 'traffic',
    description: 'Westside traffic along Sunland Park',
  },
  {
    id: 'air-force-drive',
    name: 'Air Force Drive',
    location: 'Air Force Drive & Loop 375',
    latitude: 31.769,
    longitude: -106.269,
    highway: 'Other',
    neighborhood: 'Eastside',
    imageUrl: 'https://images.unsplash.com/photo-1446776653964-20c1d3a81b06?w=800&q=80',
    lastUpdated: new Date().toISOString(),
    status: 'active',
    cameraType: 'traffic',
    description: 'Traffic monitoring near Air Force Drive',
  },
];

export function getFallbackMockCameras(): Camera[] {
  return MOCK_CAMERAS;
}
